### ISSUE TITLE
It doesn't work on little zombies

### ISSUE THREAD

**Issue by 19300000** [iChun/Mob-Dismemberment#7]
why?

**Comment by iChun** [comment]
because the baby zombies haven't rotted as much and their ligaments means the body doesn't fall apart on death.

**Comment by Hotten1** [comment]
Can you modify the bonding strength of the ligaments in a config? i want to configure the baby zombies to work like normal ones.

**Comment by iChun** [comment]
No, unfortunately the real answer is baby zombies came to be after the creation and development of this mod and my focus has been on other projects, and this mod was slated for a full rewrite, so I never got round to adding support for baby zombies.
